### ISSUE TITLE
In course with HandsOn labs, the lab video will be missing in the downloaded file.

### ISSUE THREAD

**Issue by Alex-ll-2021** [r0oth3x49/acloud-dl#96]
In course with HandsOn labs, the lab video will be missing in the downloaded file.

**Comment by Alex-ll-2021** [comment]
Because it has to click on start the lab. Then its open
https://learn.acloud.guru/handson/<String>/course/az-900-microsoft-azure-fundamentals

**Comment by r0oth3x49** [comment]
@Alex-ll-2021 yes its clearly mentioned in the readme that you need to START course to be able to download it using acloud-dl

**Comment by skmd0** [comment]
My personal opinion on this issue is that it would most likely be very hard to implement. Starting a Hands-On Lab basically makes a new VM instance for you and sometimes you have to wait up to 8 minutes for instance to be ready for you (Linux VM for example). I understand that videos are not hosted in a VM, but the access to those videos is generated when you start the lab (signature+keypair in url).

Example of an video URL:

```
https://content.acloud.guru/4133dcfc-9ca8-44c5-ba11-aebf2cf3c208/1351620000001-000020.mp4?Expires=1666221774&Signature=PBMdwiLE9epHnagIPS1SJZnCBSpqbxhDPLKBl3jtoE5yCfGOTQJKux5AsapN6m2KFJRcDVKiwfVuFOTczP5lhwm1FX9NUkmTl2UN883avnmtZAX4iVlxAsRto6YuzfAoFrsFjHXfE2cgvVrXDlPECNcuzbthG7K9PEx54vj6teYPP0lU+szb7EJ1O7j9mioSEH7cX4kVP8toxcFEHG/RiPXXbZrm9E9sUXJ/lrdIkSI+thZlJ4L4lXV6PODg8g/RjVmAVwbXKzmj7JFOJNXSwkb1IflZnYD5OvM1q1BHevUboqcBZm7clGMnR4cUWSofUNYvrUCT3VhcY/zQmjiKvQ==&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jb250ZW50LmFjbG91ZC5ndXJ1LzQxMzNkY2ZjLTljYTgtNDRjNS1iYTExLWFlYmYyY2YzYzIwOC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY2MjIxNzc0fX19XX0=&Key-Pair-Id=APKAILSU6JYPU7SFE6UA
```
